SELECT
    INS.NAME,
    INS.DATETIME
FROM ANIMAL_OUTS AS OUTS
    RIGHT OUTER JOIN ANIMAL_INS AS INS
        ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE OUTS.ANIMAL_ID IS NULL
ORDER BY INS.DATETIME
    LIMIT 3;